### ISSUE TITLE
SpektrumTelemetrySensor.cproj

### ISSUE THREAD

**Issue by KHeintz** [csc13/spektel-sensor#1]
Atmel Studio aborts with the following message.

spektel-sensor-master\spektel-sensor-master\project\SpektrumTelemetrySensor\SpektrumTelemetrySensor.cproj : error  : The project file could not be loaded. Could not find a part of the path. Atmel Studio missing the project file.

**Comment by csc13** [comment]
Hi,
I didn't intend to give the whole project, only the source files. I'm currently finishing the changes for REV_B. So if you want a ready working version for the board REV_B, you need to wait some more days.

Does this help you?
Regards
Chris

**Comment by csc13** [comment]
The project is available as a ZIP file and should be placed in the Atmel/6.2 folder.
See in the "project" folder!
